# Generated by Django 3.1.7 on 2021-03-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('child_name', models.CharField(max_length=200)),
                ('street_address', models.CharField(max_length=200)),
                ('city_address', models.CharField(max_length=100)),
                ('school_name', models.CharField(max_length=255)),
                ('school_address', models.CharField(max_length=255)),
                ('interests_child', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Kindergarten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kinder_name', models.CharField(choices=[('DB', 'Przedszkole w Debrznie'), ('WC', 'Przedszkole w Wierzchowie Człuwoskim'), ('JA', 'Przedszkole Jacka i Agatki w Człuchpwie'), ('BA', 'Przedszkole Bajka w Człuchowie'), ('SM', 'Przedszkole Smyk w Człuchowie'), ('PI', 'Przedszkole Piano w Człuchowie')], default='DB', max_length=255)),
                ('user_name', models.CharField(max_length=200)),
                ('child_name', models.CharField(max_length=200)),
                ('class_name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('regulations', models.CharField(choices=[('Y', 'Tak'), ('N', 'Nie')], default='Y', max_length=3)),
                ('data_enrol', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
