# Generated by Django 3.1.7 on 2021-03-18 14:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210318_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kindergarten',
            name='phone_number',
            field=models.CharField(max_length=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kindergarten',
            name='regulations',
            field=models.BooleanField(default=False),
        ),
    ]
