# Generated by Django 3.1.7 on 2021-03-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20210319_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kindergarten',
            name='phone_number',
            field=models.CharField(max_length=9),
        ),
    ]
