# Generated by Django 3.1.7 on 2021-03-20 14:14

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20210319_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kindergarten',
            name='child_name',
            field=models.CharField(max_length=200, verbose_name='Imię i nazwisko dziecka'),
        ),
        migrations.AlterField(
            model_name='kindergarten',
            name='class_name',
            field=models.CharField(max_length=50, verbose_name='Nazwa grupy przedszkolnej'),
        ),
        migrations.AlterField(
            model_name='kindergarten',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Adres mailowy rodzica(opiekuna)'),
        ),
        migrations.AlterField(
            model_name='kindergarten',
            name='kinder_name',
            field=models.CharField(choices=[('Przedszkole w Debrznie', 'Przedszkole w Debrznie'), ('Przedszkole w Wierzchowie Człuwoskim', 'Przedszkole w Wierzchowie Człuwoskim'), ('Przedszkole Jacka i Agatki w Człuchpwie', 'Przedszkole Jacka i Agatki w Człuchpwie'), ('Przedszkole Bajka w Człuchowie', 'Przedszkole Bajka w Człuchowie'), ('Przedszkole Smyk w Człuchowie', 'Przedszkole Smyk w Człuchowie'), ('Przedszkole Piano w Człuchowie', 'Przedszkole Piano w Człuchowie')], default='Przedszkole w Debrznie', max_length=255, verbose_name='Wybierz przedszkole'),
        ),
        migrations.AlterField(
            model_name='kindergarten',
            name='phone_number',
            field=models.PositiveSmallIntegerField(max_length=9, verbose_name='Nr telefonu rodzica(opiekuna)'),
        ),
        migrations.AlterField(
            model_name='kindergarten',
            name='regulations',
            field=models.BooleanField(validators=[website.models.Kindergarten.validate_regulations], verbose_name='Potwierdzam, że zapoznałem się z regulaminem'),
        ),
        migrations.AlterField(
            model_name='kindergarten',
            name='user_name',
            field=models.CharField(max_length=200, verbose_name='Imię i nazwisko rodzica(opiekuna)'),
        ),
    ]
