# Generated by Django 3.1.7 on 2021-03-21 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20210320_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kindergarten',
            name='phone_number',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^[-\\s\\./0-9]*$', 'Podaj poprawny nr tefonu - tylko liczby')], verbose_name='Nr telefonu rodzica(opiekuna)'),
        ),
    ]
