# Generated by Django 3.1.7 on 2021-03-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20210323_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='camps',
            name='child_born_city',
            field=models.CharField(max_length=100, null=True, verbose_name='Miejsce urodzenia dziecka'),
        ),
        migrations.AlterField(
            model_name='camps',
            name='child_birth_date',
            field=models.DateField(verbose_name='Data urodzenia (RRRR-MM-DD)'),
        ),
    ]
