# Generated by Django 3.1.7 on 2021-03-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20210323_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camps',
            name='child_birth_date',
            field=models.DateTimeField(verbose_name='Data urodzenia (RRRR-MM-DD)'),
        ),
    ]
