# Generated by Django 3.1.7 on 2021-03-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20210323_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camps',
            name='child_birth_date',
            field=models.CharField(max_length=10, verbose_name='Data urodzenia (RRRR-MM-DD)'),
        ),
    ]
