# Generated by Django 3.1.7 on 2021-03-26 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20210323_1957'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Camp',
        ),
    ]
