# Generated by Django 3.1.7 on 2021-03-26 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_delete_camp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Camps',
            new_name='Camp',
        ),
    ]
