# Generated by Django 3.1.7 on 2021-03-26 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20210326_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayCamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=255, verbose_name='Imię i nazwisko dziecka')),
                ('child_pesel', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[-\\s\\./0-9]*$', 'Podaj poprawny nr tefonu - tylko liczby')], verbose_name='PESEL')),
                ('child_birth_date', models.CharField(max_length=10, verbose_name='Data urodzenia (RRRR-MM-DD)')),
                ('parent_name', models.CharField(max_length=255, verbose_name='Imię i nazwisko rodzica/opiekuna')),
                ('street_address', models.CharField(max_length=254, verbose_name='Adres zamieszkania (ulica, nr domu, nr mieszkania)')),
                ('postal_code', models.CharField(max_length=6, verbose_name='Kod pocztowy')),
                ('city_address', models.CharField(max_length=100, verbose_name='Miejscowość')),
                ('parent_email', models.EmailField(max_length=254, verbose_name='Adres mailowy rodzica/opiekuna')),
                ('phone_parent_1', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^[-\\s\\./0-9]*$', 'Podaj poprawny nr tefonu - tylko liczby')], verbose_name='Telefon kontaktowy nr 1 do rodzica/opiekuna')),
                ('phone_parent_2', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^[-\\s\\./0-9]*$', 'Podaj poprawny nr tefonu - tylko liczby')], verbose_name='Telefon kontaktowy nr 2 do rodzica/opiekuna')),
                ('receiving_person_1', models.CharField(max_length=255, verbose_name='Imię i nazwisko rodzica/opiekuna')),
                ('relationship_child_1', models.CharField(max_length=255, verbose_name='Relacje z dzieckiem (dziadek, wujek, sąsiadka)')),
                ('phone_receiving_1', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^[-\\s\\./0-9]*$', 'Podaj poprawny nr tefonu - tylko liczby')], verbose_name='Telefon kontaktowy do osoby upoważnionej do odbioru')),
                ('receiving_person_2', models.CharField(max_length=255, verbose_name='Imię i nazwisko rodzica/opiekuna')),
                ('relationship_child_2', models.CharField(max_length=255, verbose_name='Relacje z dzieckiem (dziadek, wujek, sąsiadka)')),
                ('phone_receiving_2', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^[-\\s\\./0-9]*$', 'Podaj poprawny nr tefonu - tylko liczby')], verbose_name='Telefon kontaktowy do osoby upoważnionej do odbioru')),
                ('receiving_person_3', models.CharField(max_length=255, verbose_name='Imię i nazwisko rodzica/opiekuna')),
                ('relationship_child_3', models.CharField(max_length=255, verbose_name='Relacje z dzieckiem (dziadek, wujek, sąsiadka)')),
                ('phone_receiving_3', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^[-\\s\\./0-9]*$', 'Podaj poprawny nr tefonu - tylko liczby')], verbose_name='Telefon kontaktowy do osoby upoważnionej do odbioru')),
            ],
        ),
    ]
