# Generated by Django 3.1.7 on 2021-03-27 13:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_daycamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='daycamp',
            name='data_enrol',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='daycamp',
            name='phone_receiving_1',
            field=models.CharField(max_length=9, null=True, validators=[django.core.validators.RegexValidator('^[-\\s\\./0-9]*$', 'Podaj poprawny nr tefonu - tylko liczby')], verbose_name='Telefon kontaktowy do osoby upoważnionej do odbioru'),
        ),
        migrations.AlterField(
            model_name='daycamp',
            name='phone_receiving_2',
            field=models.CharField(max_length=9, null=True, validators=[django.core.validators.RegexValidator('^[-\\s\\./0-9]*$', 'Podaj poprawny nr tefonu - tylko liczby')], verbose_name='Telefon kontaktowy do osoby upoważnionej do odbioru'),
        ),
        migrations.AlterField(
            model_name='daycamp',
            name='phone_receiving_3',
            field=models.CharField(max_length=9, null=True, validators=[django.core.validators.RegexValidator('^[-\\s\\./0-9]*$', 'Podaj poprawny nr tefonu - tylko liczby')], verbose_name='Telefon kontaktowy do osoby upoważnionej do odbioru'),
        ),
        migrations.AlterField(
            model_name='daycamp',
            name='receiving_person_1',
            field=models.CharField(max_length=255, null=True, verbose_name='Imię i nazwisko rodzica/opiekuna'),
        ),
        migrations.AlterField(
            model_name='daycamp',
            name='receiving_person_2',
            field=models.CharField(max_length=255, null=True, verbose_name='Imię i nazwisko rodzica/opiekuna'),
        ),
        migrations.AlterField(
            model_name='daycamp',
            name='receiving_person_3',
            field=models.CharField(max_length=255, null=True, verbose_name='Imię i nazwisko rodzica/opiekuna'),
        ),
        migrations.AlterField(
            model_name='daycamp',
            name='relationship_child_1',
            field=models.CharField(max_length=255, null=True, verbose_name='Relacje z dzieckiem (dziadek, wujek, sąsiadka)'),
        ),
        migrations.AlterField(
            model_name='daycamp',
            name='relationship_child_2',
            field=models.CharField(max_length=255, null=True, verbose_name='Relacje z dzieckiem (dziadek, wujek, sąsiadka)'),
        ),
        migrations.AlterField(
            model_name='daycamp',
            name='relationship_child_3',
            field=models.CharField(max_length=255, null=True, verbose_name='Relacje z dzieckiem (dziadek, wujek, sąsiadka)'),
        ),
    ]
