# Generated by Django 3.1.7 on 2021-03-28 22:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20210327_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daycamp',
            name='child_birth_date',
            field=models.CharField(max_length=10, verbose_name='Data urodzenia dziecka (RRRR-MM-DD)'),
        ),
        migrations.AlterField(
            model_name='daycamp',
            name='child_pesel',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[-\\s\\./0-9]*$', 'Podaj poprawny nr tefonu - tylko liczby')], verbose_name='PESEL dziecka'),
        ),
        migrations.AlterField(
            model_name='daycamp',
            name='receiving_person_1',
            field=models.CharField(max_length=255, null=True, verbose_name='Imię i nazwisko osoby upoważnionej do dobioru dziecka'),
        ),
        migrations.AlterField(
            model_name='daycamp',
            name='receiving_person_2',
            field=models.CharField(max_length=255, null=True, verbose_name='Imię i nazwisko osoby upoważnionej do dobioru dziecka'),
        ),
        migrations.AlterField(
            model_name='daycamp',
            name='receiving_person_3',
            field=models.CharField(max_length=255, null=True, verbose_name='Imię i nazwisko osoby upoważnionej do dobioru dziecka'),
        ),
    ]
