# Generated by Django 3.1.7 on 2021-04-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20210329_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='daycamp',
            name='date_daycamp',
            field=models.CharField(choices=[('I turnus', 'I turnus'), ('II turnus', 'II turnus')], default='I turnus', max_length=9, verbose_name='Wybierz termin półkolonii'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='interests_child',
            field=models.CharField(max_length=255, verbose_name='Zainteresowania dziecka (wymienić kilka najważniejszych oddzielając przecinkiem) '),
        ),
    ]
