# Generated by Django 3.1.7 on 2021-04-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_auto_20210406_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daycamp',
            name='date_daycamp',
            field=models.CharField(choices=[('I termin', 'I termin'), ('II termin', 'II termin')], default='I termin', max_length=9, verbose_name='Wybierz termin półkolonii'),
        ),
    ]
