# Generated by Django 3.1.7 on 2021-07-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20210406_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kindergarten',
            name='kinder_name',
            field=models.CharField(choices=[('Przedszkole w Debrznie', 'Przedszkole w Debrznie'), ('Przedszkole w Wierzchowie Człuwoskim', 'Przedszkole w Wierzchowie Człuwoskim'), ('Przedszkole Jacka i Agatki w Człuchowie', 'Przedszkole Jacka i Agatki w Człuchowie'), ('Przedszkole Bajka w Człuchowie', 'Przedszkole Bajka w Człuchowie'), ('Przedszkole Smyk w Człuchowie', 'Przedszkole Smyk w Człuchowie'), ('Przedszkole Piano w Człuchowie', 'Przedszkole Piano w Człuchowie')], default='Przedszkole w Debrznie', max_length=255, verbose_name='Wybierz przedszkole'),
        ),
    ]
