# Generated by Django 3.1.7 on 2021-09-11 13:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_auto_20210825_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kindergarten',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Adres mailowy rodzica (opiekuna)'),
        ),
        migrations.AlterField(
            model_name='kindergarten',
            name='kinder_name',
            field=models.CharField(choices=[('Przedszkole w Debrznie', 'Przedszkole w Debrznie'), ('Przedszkole w Wierzchowie Człuwoskim', 'Przedszkole w Wierzchowie Człuwoskim'), ('Przedszkole im. Jacka i Agatki w Człuchowie', 'Przedszkole im. Jacka i Agatki w Człuchowie'), ('Przedszkole Bajka w Człuchowie', 'Przedszkole Bajka w Człuchowie'), ('Przedszkole Smyk w Człuchowie', 'Przedszkole Smyk w Człuchowie'), ('Przedszkole Piano w Człuchowie', 'Przedszkole Piano w Człuchowie')], default='Przedszkole w Debrznie', max_length=255, verbose_name='Wybierz przedszkole'),
        ),
        migrations.AlterField(
            model_name='kindergarten',
            name='phone_number',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^[-\\s\\./0-9]*$', 'Podaj poprawny nr tefonu - tylko liczby')], verbose_name='Nr telefonu rodzica (opiekuna)'),
        ),
        migrations.AlterField(
            model_name='kindergarten',
            name='user_name',
            field=models.CharField(max_length=200, verbose_name='Imię i nazwisko rodzica (opiekuna)'),
        ),
    ]
