# Generated by Django 3.1.7 on 2021-09-28 19:21

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_auto_20210911_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='regulations',
            field=models.BooleanField(default=False, validators=[website.models.Camp.validate_regulations], verbose_name='Reglamin'),
        ),
        migrations.AddField(
            model_name='daycamp',
            name='regulations',
            field=models.BooleanField(default=False, validators=[website.models.DayCamp.validate_regulations], verbose_name='Reglamin'),
        ),
        migrations.AddField(
            model_name='kindergarten',
            name='regulations_image',
            field=models.BooleanField(default=False, verbose_name='Wizerunek'),
        ),
        migrations.AlterField(
            model_name='kindergarten',
            name='regulations',
            field=models.BooleanField(validators=[website.models.Kindergarten.validate_regulations], verbose_name='Reglamin'),
        ),
    ]
