# Generated by Django 3.1.7 on 2021-04-06 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='join',
            old_name='email',
            new_name='newsletter_email',
        ),
        migrations.RenameField(
            model_name='join',
            old_name='timestamp',
            new_name='newsletter_timestamp',
        ),
    ]
