# Generated by Django 3.1.7 on 2021-04-08 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210408_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replay_name', models.CharField(max_length=100, verbose_name='Podaj imię')),
                ('replay_content', models.TextField(verbose_name='Wpisz treść')),
                ('replay_date_added', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repleys', to='blog.comment')),
            ],
        ),
    ]
