# Generated by Django 3.1.7 on 2021-04-08 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_replycomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replycomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replays', to='blog.comment'),
        ),
    ]
